name: Continuous Integration EPPlus project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore ./src/SpreadsheetWriter.EPPlus/SpreadsheetWriter.EPPlus.csproj
    - name: Build
      run: dotnet build ./src/SpreadsheetWriter.EPPlus/SpreadsheetWriter.EPPlus.csproj --no-restore --configuration Release
    - name: Test with dotnet
      run: dotnet test --logger trx --results-directory "TestResults-${{GITHUB_RUN_ID}}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results-${{GITHUB_RUN_ID}}
        path: TestResults-${{GITHUB_RUN_ID}}
    - name: Pack
      run: dotnet pack ./src/SpreadsheetWriter.EPPlus/SpreadsheetWriter.EPPlus.csproj --no-build --configuration Release
    - name: Publish
      run: dotnet nuget push "./src/SpreadsheetWriter.EPPlus/bin/Release/SpreadsheetWriter.EPPlus.*.nupkg" --source https://nuget.pkg.github.com/wouterfennis/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
