name: Continuous Integration Abstraction project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/SpreadsheetWriter.Abstractions/SpreadsheetWriter.Abstractions.csproj
    - name: Build
      run: dotnet build ./src/SpreadsheetWriter.Abstractions/SpreadsheetWriter.Abstractions.csproj --no-restore --configuration Release
    - name: Pack
      run: dotnet pack ./src/SpreadsheetWriter.Abstractions/SpreadsheetWriter.Abstractions.csproj --no-build --configuration Release
    - name: Publish
      run: dotnet nuget push "./src/SpreadsheetWriter.Abstractions/bin/Release/SpreadsheetWriter.Abstractions.*.nupkg" --source https://nuget.pkg.github.com/wouterfennis/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
