name: Build spreadsheet writer

on:
  push:
    branches: [ develop ]
    paths:
    - 'src/**'
    - 'test/**'
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with dotnet
      run: dotnet test --logger trx --results-directory "TestResults-${{ GITHUB_RUN_ID }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results-${{ GITHUB_RUN_ID }}
        path: TestResults-${{ GITHUB_RUN_ID }}
        if: ${{ always() }}
